// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/extmatperez/meli_bootcamp_go_w2-2/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// BuyerRepositoryMock is an autogenerated mock type for the BuyerRepository type
type BuyerRepositoryMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BuyerRepositoryMock) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, cardNumberID
func (_m *BuyerRepositoryMock) Exists(ctx context.Context, cardNumberID string) bool {
	ret := _m.Called(ctx, cardNumberID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, cardNumberID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *BuyerRepositoryMock) Get(ctx context.Context, id int) (entities.Buyer, error) {
	ret := _m.Called(ctx, id)

	var r0 entities.Buyer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Buyer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Buyer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Buyer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *BuyerRepositoryMock) GetAll(ctx context.Context) ([]entities.Buyer, error) {
	ret := _m.Called(ctx)

	var r0 []entities.Buyer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Buyer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Buyer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Buyer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, b
func (_m *BuyerRepositoryMock) Save(ctx context.Context, b entities.Buyer) (int, error) {
	ret := _m.Called(ctx, b)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Buyer) (int, error)); ok {
		return rf(ctx, b)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Buyer) int); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Buyer) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, b
func (_m *BuyerRepositoryMock) Update(ctx context.Context, b entities.Buyer) error {
	ret := _m.Called(ctx, b)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Buyer) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBuyerRepositoryMock creates a new instance of BuyerRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuyerRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuyerRepositoryMock {
	mock := &BuyerRepositoryMock{}
	mock.Mock.Test(t)

	return mock
}
