// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/extmatperez/meli_bootcamp_go_w2-2/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// SectionRepositoryMock is an autogenerated mock type for the SectionRepository type
type SectionRepositoryMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SectionRepositoryMock) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, sectionNumber
func (_m *SectionRepositoryMock) Exists(ctx context.Context, sectionNumber int) bool {
	ret := _m.Called(ctx, sectionNumber)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, sectionNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *SectionRepositoryMock) Get(ctx context.Context, id int) (entities.Section, error) {
	ret := _m.Called(ctx, id)

	var r0 entities.Section
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entities.Section, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entities.Section); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Section)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *SectionRepositoryMock) GetAll(ctx context.Context) ([]entities.Section, error) {
	ret := _m.Called(ctx)

	var r0 []entities.Section
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Section, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Section); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Section)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, s
func (_m *SectionRepositoryMock) Save(ctx context.Context, s entities.Section) (int, error) {
	ret := _m.Called(ctx, s)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Section) (int, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Section) int); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Section) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, s
func (_m *SectionRepositoryMock) Update(ctx context.Context, s entities.Section) error {
	ret := _m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Section) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSectionRepositoryMock creates a new instance of SectionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSectionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SectionRepositoryMock {
	mock := &SectionRepositoryMock{}
	mock.Mock.Test(t)

	return mock
}
