// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/extmatperez/meli_bootcamp_go_w2-2/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// SellerRepositoryMock is an autogenerated mock type for the SellerRepository type
type SellerRepositoryMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SellerRepositoryMock) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, cid
func (_m *SellerRepositoryMock) Exists(ctx context.Context, cid int) bool {
	ret := _m.Called(ctx, cid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, cid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *SellerRepositoryMock) Get(ctx context.Context, id int) (*entities.Seller, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entities.Seller, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entities.Seller); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Seller)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *SellerRepositoryMock) GetAll(ctx context.Context) ([]entities.Seller, error) {
	ret := _m.Called(ctx)

	var r0 []entities.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Seller, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Seller); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Seller)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, s
func (_m *SellerRepositoryMock) Save(ctx context.Context, s entities.Seller) (int, error) {
	ret := _m.Called(ctx, s)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Seller) (int, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Seller) int); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Seller) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, s
func (_m *SellerRepositoryMock) Update(ctx context.Context, s entities.Seller) error {
	ret := _m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Seller) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSellerRepositoryMock creates a new instance of SellerRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSellerRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SellerRepositoryMock {
	mock := &SellerRepositoryMock{}
	mock.Mock.Test(t)

	return mock
}
