with-expecter: True
packages:
  github.com/extmatperez/meli_bootcamp_go_w2-2/internal/locality:
    interfaces:
      LocalityService:
        config:
          outpkg: "mocks"
          dir: "{{.InterfaceDir}}/mocks/"
          with-expecter: False
        LocalityRepository:
          config:
            outpkg: "mocks"
            dir: "{{.InterfaceDir}}/mocks/"
            with-expecter: False
  github.com/extmatperez/meli_bootcamp_go_w2-2/internal/purchaseOrder:
    interfaces:
      PurchaseOrderRepository:
        config:
          outpkg: "mocks"
          dir: "{{.InterfaceDir}}/mocks/"
          with-expecter: False
      PurchaseOrderService:
        config:
          outpkg: "mocks"
          dir: "{{.InterfaceDir}}/mocks/"
          with-expecter: False