package mocks

import (
	context "context"

	domain "github.com/extmatperez/meli_bootcamp_go_w2-2/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type SellerRepositoryMock struct {
	mock.Mock
}

func NewSellerRepositoryMock() *SellerRepositoryMock {
	return &SellerRepositoryMock{}
}

// Delete provides a mock function with given fields: ctx, id
func (m *SellerRepositoryMock) Delete(ctx context.Context, id int) error {
	ret := m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, cid
func (m *SellerRepositoryMock) Exists(ctx context.Context, cid int) bool {
	ret := m.Called(ctx, cid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, cid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (m *SellerRepositoryMock) Get(ctx context.Context, id int) (*domain.Seller, error) {
	ret := m.Called(ctx, id)

	var r0 *domain.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Seller, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Seller); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Seller)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (m *SellerRepositoryMock) GetAll(ctx context.Context) ([]domain.Seller, error) {
	ret := m.Called(ctx)

	var r0 []domain.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Seller, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Seller); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Seller)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, s
func (m *SellerRepositoryMock) Save(ctx context.Context, s domain.Seller) (int, error) {
	ret := m.Called(ctx, s)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Seller) (int, error)); ok {
		return rf(ctx, s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Seller) int); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Seller) error); ok {
		r1 = rf(ctx, s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, s
func (m *SellerRepositoryMock) Update(ctx context.Context, s domain.Seller) error {
	ret := m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Seller) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
