definitions:
  dtos.CreateSellerRequestDTO:
    properties:
      address:
        type: string
      cid:
        type: integer
      company_name:
        type: string
      telephone:
        type: string
    required:
    - address
    - cid
    - company_name
    - telephone
    type: object
  dtos.UpdateSellerRequestDTO:
    properties:
      address:
        type: string
      cid:
        type: integer
      company_name:
        type: string
      telephone:
        type: string
    type: object
  handler.request:
    properties:
      current_capacity:
        type: integer
      current_temperature:
        type: integer
      maximum_capacity:
        type: integer
      minimum_capacity:
        type: integer
      minimum_temperature:
        type: integer
      product_type_id:
        type: integer
      section_number:
        type: integer
      warehouse_id:
        type: integer
    type: object
  handler.requestProduct:
    properties:
      description:
        type: string
      expiration_rate:
        type: integer
      freezing_rate:
        type: integer
      height:
        type: number
      length:
        type: number
      netweight:
        type: number
      product_code:
        type: string
      product_type_id:
        type: integer
      recommended_freezing_temperature:
        type: number
      seller_id:
        type: integer
      width:
        type: number
    type: object
  web.response:
    properties:
      data: {}
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI - Sprint 1 - Grupo 2
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API - Sprint 1 - Grupo 2
  version: "1.0"
paths:
  /api/v1/Products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Product
      parameters:
      - description: ID of a Product to be excluded
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/web.response'
      summary: Delete Product
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Update the details of a Product
      parameters:
      - description: ID of Products to be updated
        in: path
        name: id
        required: true
        type: string
      - description: Updated Product details
        in: body
        name: Products
        required: true
        schema:
          $ref: '#/definitions/handler.requestProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Update Product
      tags:
      - Products
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: getAll products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: List products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create Product
      parameters:
      - description: Product to Create
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/handler.requestProduct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
      summary: Create Product
      tags:
      - Products
  /api/v1/products/{id}:
    get:
      consumes:
      - application/json
      description: Get the details of a Products
      parameters:
      - description: ID of Product to be searched
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Get Product
      tags:
      - Products
  /api/v1/sections:
    get:
      consumes:
      - application/json
      description: getAll sections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: List sections
      tags:
      - Sections
    post:
      consumes:
      - application/json
      description: Create sections
      parameters:
      - description: Section to Create
        in: body
        name: Section
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
      summary: Create Section
      tags:
      - Sections
  /api/v1/sections/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Section
      parameters:
      - description: ID of a Section to be excluded
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/web.response'
      summary: Delete Section
      tags:
      - Sections
    get:
      consumes:
      - application/json
      description: Get the details of a Section
      parameters:
      - description: ID of Section to be searched
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Get Section
      tags:
      - Sections
    patch:
      consumes:
      - application/json
      description: Update the details of a Section
      parameters:
      - description: ID of Section to be updated
        in: path
        name: id
        required: true
        type: string
      - description: Updated Section details
        in: body
        name: Sections
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Update Section
      tags:
      - Sections
  /api/v1/sellers:
    get:
      consumes:
      - application/json
      description: getAll sellers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: List sellers
      tags:
      - Sellers
    post:
      consumes:
      - application/json
      description: Create sellers
      parameters:
      - description: Seller to Create
        in: body
        name: Seller
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateSellerRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Create Sellers
      tags:
      - Sellers
  /api/v1/sellers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Sellers
      parameters:
      - description: ID of a Sellers to be excluded
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Delete Sellers
      tags:
      - Sellers
    get:
      consumes:
      - application/json
      description: Get the details of a Sellers
      parameters:
      - description: ID of Sellers to be searched
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Get Sellers
      tags:
      - Sellers
    patch:
      consumes:
      - application/json
      description: Update the details of a Sellers
      parameters:
      - description: ID of Sellers to be updated
        in: path
        name: id
        required: true
        type: string
      - description: Updated Sellers details
        in: body
        name: Sellers
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateSellerRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Update Sellers
      tags:
      - Sellers
swagger: "2.0"
